---
- name: Wordpressをダウンロード
  get_url:
    url: https://ja.wordpress.org/wordpress-{{ wp_version }}-ja.tar.gz
    dest: /srv/wordpress-{{ wp_version }}-ja.tar.gz
    sha256sum: "{{ wp_sha256sum }}"

- name: Wordpress圧縮ファイルを展開
  unarchive:
    src: /srv/wordpress-{{ wp_version }}-ja.tar.gz
    dest: /srv/
    copy: no

- name: \"wordpress\"グループを追加
  group:
    name: wordpress

- name: \"wordpress\"ユーザーを追加
  user:
    name: wordpress
    group: wordpress
    home: /srv/wordpress/

- name: Wordpress用データベースを作成
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Wordpress用データベースユーザーを作成
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present

- name: Wordpress設定ファイルを配置
  template:
    src: wp-config.php
    dest: /srv/wordpress/wp-config.php

- name: Wordpressインストールディレクトリ下のオーナーを変更
  file:
    path: /srv/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: yes

- name: php-fpm起動
  service:
    name: php-fpm
    state: started
    enabled: true
